#!/bin/bash
read -p "Enter the number" num
temp=$num
rev=0
while [ $num -ne 0 ]
do
rem=$((num%10))
rev=$((rem+rev*10))
echo $rem
num=$((num/10))


done
echo $rev

if [ $temp -eq $rev ]
then
echo "Given number is palindrome"

fi
    
